function(get_project_prop PROJ PROP)
    if(DEFINED ARGV2)
        set(DEST "${ARGV2}")
    else()
        string(MAKE_C_IDENTIFIER ${PROJ}_${PROP} DEST)
    endif()
    ExternalProject_Get_Property(${PROJ} ${PROP})
    set(${DEST} "${${PROP}}" PARENT_SCOPE)
endfunction(get_project_prop)